version: '3.8'

networks:
  shashank-net:
    driver: bridge

volumes:
  shashank_db_data:

services:
  shashank-db:
    image: postgres:17-alpine
    container_name: shashank-db
    environment:
      POSTGRES_USER: shashank
      POSTGRES_PASSWORD: shashank
      POSTGRES_DB: shashankdb
    ports:
      - "35434:5432"
    volumes:
      - shashank_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shashank -d shashankdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    networks:
      - shashank-net

  shashank-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shashank-app
    depends_on:
      shashank-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://shashank-db:5432/shashankdb
      SPRING_DATASOURCE_USERNAME: shashank
      SPRING_DATASOURCE_PASSWORD: shashank
    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - shashank-net

